name: Automa√ß√£o Cartola BigQuery

on:
  schedule:
    # Roda a cada 1 hora (no minuto 0)
    # Ex: 10:00, 11:00, 12:00...
    - cron: '0 * * * *'
  
  # Permite rodar manualmente clicando no bot√£o "Run workflow"
  workflow_dispatch:

jobs:
  coleta_e_ia:
    runs-on: ubuntu-latest

    steps:
      - name: üì• Checkout do C√≥digo
        uses: actions/checkout@v3

      - name: üêç Configurar Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - - name: üì¶ Instalar Depend√™ncias
        run: |
          python -m pip install --upgrade pip
          pip install pandas-gbq
          pip install -r requirements.txt

      - name: üöÄ Executar Coletor
        env:
          # Mapeando os Secrets do GitHub para o Python
          CARTOLA_BEARER_TOKEN: ${{ secrets.CARTOLA_BEARER_TOKEN }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          GCP_SERVICE_ACCOUNT: ${{ secrets.GCP_SERVICE_ACCOUNT }}
        run: python coletor.py